###
POST https://backflow-service-app--bb.blackpond-195f2b5d.northcentralusstage.azurecontainerapps.io/Init/installer/main?recursive=true

###
POST https://backflow-service-app--bb.blackpond-195f2b5d.northcentralusstage.azurecontainerapps.io/Update/arcade/226c103b56a979243f08032e6cddb4deb66ea54b

###

